language: node_js
sudo: false
node_js:
- 10
install:
- npm i
- npm i codecov -g
script:
- npm run coverage
- codecov
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: patryk_walach@outlook.com
  api_key:                
    secure: S0dq9NDoZBn37fI7oBH1gKTFlvXgnVanByMzxxO8MkET4R0eHbyDJgurckRysKqIb2bV+yPT7bRw3WqiD2QJUROkQtt2X+9aDWcXqdXNimmRd3CPYHS74dttg2zV7PF+qnco7pRnQ0L0GsGZgwyrKPQ581PJ61x9RHAul6KnsoWlWITRSp4YJ7fGpfiUkykq6mVE4IZ9nPY2PNREgqYmmvQl3PE6k4GiFCeEED/5+Ha/qC7zgYeWjRnKp+PETGwDxY+GLbmTCCI6Uh6a+RIKo1lktn6RRViOXfwpRED2XgbaG0dwinpmurjhslujQpolSxANqXPhZzwNB4xCsq7VEnqMlBBxvvB7pc1wFJ/mV4kVd/rulv3JURPPEFoix3Ke4Ke1OBYdSKXWECWefiBfZwTwr1kFsf3CnLeE8wzELhnjRhNZq6jU5OvOa1epwsqwCS2KilyaadUdPCz8myVRfpWDb1bf5M1ZvXIUPEWxgYsU3Bny8GdX+N0FmaOwlfILah9WacqOxNPDmiSRZ9KG476bnnZ+B6jpur8BzjjOipRoGikYXUbAxGLzwZX9RYvEkgzE4HE1QhGAHxrVTp1p6mI98gXZxLMy7lEv02IvNKCzFwdxzbRoGFEB8dROd99ucveilY6ckoMJ1KTVaairmzfNfQpf9/vsmRRdHYdECDM=
  on:
    tags: true
